service: ocp
image: stawan15/ocp

servers:
  web:
    - 192.46.230.54

ssh:
  user: deploy

registry:
  username: stawan15
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true

proxy:
  ssl: false
  host: 192.46.230.54
  app_port: 3000
  healthcheck:
    path: /up
    interval: 5
    timeout: 5

boot:
  wait: 30

volumes:
  - "ocp_storage:/rails/storage"

asset_path: /rails/public/assets