upstream <site-name>{
        server unix:/srv/www/apps/<project-name>/current/tmp/sockets/<service-name>.sock max_fails=3  fail_timeout=60s;
}

server {
    server_name <domain-name>;
    listen 80;
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    root /srv/www/apps/<project-name>/current;

    try_files $uri/index.html $uri @<site-name>;

    location @<site-name> {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # When leave under Amazon Load Balancer
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Ssl on;
        #proxy_set_header  X-Forwarded-Port $server_port;
        proxy_set_header  X-Forwarded-Host $host;
        proxy_redirect off;
        proxy_pass http://<site-name>;
    }
    # Allow cable (WSS)
    location /cable {
        proxy_pass http://<site-name>;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Ssl on;
        #proxy_set_header  X-Forwarded-Port $server_port;
        proxy_set_header  X-Forwarded-Host $host;
    }
    # Allow Asset css image js css
    location ~* \.(assets|images|javascripts|stylesheets|system)/ {
        root /srv/www/apps/<project-name>/current/public;
        expires max;
        add_header Pragma public;
        add_header Cache-Control public;
    }

    location ~ /\.well-known/ {
        root /srv/www/apps/<project-name>/current/public;
        allow all;
    }
    # Allow picture css js file
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        root /srv/www/apps/<project-name>/current/public;
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public";
        try_files $uri @<site-name>;
    }

    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 10;

}